version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
    - DATABASE_URL=postgresql://dev_user:my_dev_password@db/Abi_Inference
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Abi_Inference
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: my_dev_password
